Repository zalando/spilo, pull requests merged in 2024-12, with the labels that each got.

#1026 fix: wrong regex for wal retention
  postgres-appliance/scripts/postgres_backup.sh
Labels: bugfix

#1050 Integrate Patroni 4.x
  ENVIRONMENT.rst
  kubernetes/spilo_kubernetes.yaml
  postgres-appliance/Dockerfile
  postgres-appliance/scripts/configure_spilo.py
Labels: major

#1058 [trigger] fix: wrong regex for wal retention (#1026)
  postgres-appliance/scripts/postgres_backup.sh
Labels: bugfix

#1060 Fix comment in tests
  postgres-appliance/tests/test_spilo.sh
Labels: minor

#1061 [Patroni4] change no_master and master as argument
  postgres-appliance/runit/pgqd/run
  postgres-appliance/scripts/callback_aws.py
  postgres-appliance/scripts/callback_role.py
  postgres-appliance/scripts/configure_spilo.py
  postgres-appliance/scripts/on_role_change.sh
  postgres-appliance/scripts/patroni_wait.sh
  postgres-appliance/scripts/wale_restore.sh
Labels: bugfix

#1063 Update publish pipeline deps versions
  .github/workflows/publish-ghcr-container.yaml
Labels: minor
